const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.yagames_sdk,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Car,
		C3.Behaviors.MoveTo,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.yagames_sdk.Acts.GameplayAPIStart,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.yagames_sdk.Acts.ShowFullscreenAD,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADOpen,
		C3.Plugins.yagames_sdk.Acts.GameplayAPIStop,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADClose,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADError,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADOffline,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.yagames_sdk.Acts.LoadingAPIReady,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Exps.choose
	];
};
self.C3_JsPropNameTable = [
	{KnopDom: 0},
	{KnopPause: 0},
	{KnopSound: 0},
	{MiniSticki: 0},
	{Якорь: 0},
	{Yakorr: 0},
	{Kozyrok: 0},
	{TextKok: 0},
	{TextKyzyl: 0},
	{Timer: 0},
	{TextTimer: 0},
	{WinKok: 0},
	{WinKyzyl: 0},
	{TextKyzylChet: 0},
	{TextKokChet: 0},
	{Твинанимация: 0},
	{ItogKok: 0},
	{ItogKyzyl: 0},
	{KnopChel1: 0},
	{KnopChel2: 0},
	{KnopDomoy: 0},
	{KnopPlay: 0},
	{KnopReplay: 0},
	{Синусоида: 0},
	{KnopTurnir: 0},
	{BackgroundTank: 0},
	{Jizn: 0},
	{Физика: 0},
	{Твёрдый: 0},
	{Derevo: 0},
	{Krug: 0},
	{Clik: 0},
	{Поворот: 0},
	{Таймер: 0},
	{TankKok: 0},
	{KirpichTail: 0},
	{TankKyzyl: 0},
	{Пуля: 0},
	{PulyaTank: 0},
	{BoomTank: 0},
	{TankKyzyl2: 0},
	{TankKok2: 0},
	{BackgroundTank2: 0},
	{OgradaTail: 0},
	{hp: 0},
	{PulyaKok: 0},
	{PulyaKyzyl: 0},
	{Blackground: 0},
	{Keyboard: 0},
	{Kok: 0},
	{Kyzyl: 0},
	{Touch: 0},
	{Trigg: 0},
	{Trigg2: 0},
	{MFon: 0},
	{MPodskazka: 0},
	{MStrelka: 0},
	{Audio: 0},
	{Browser: 0},
	{GamePush: 0},
	{Winngga: 0},
	{YandexGamesSDK: 0},
	{LocalStor: 0},
	{Naprav: 0},
	{BalloonKok: 0},
	{BalloonKyzyl: 0},
	{BaSetkaKok: 0},
	{BaSetkaKyzyl: 0},
	{StenaKirpich: 0},
	{BVolna: 0},
	{BZvezda: 0},
	{BVolna2: 0},
	{BTochki: 0},
	{ArrowKok: 0},
	{BackgroundBow: 0},
	{ArrowKyzyl: 0},
	{BowKok: 0},
	{BowKyzyl: 0},
	{Ryba: 0},
	{BackgroundLovi: 0},
	{RybaRukaKok: 0},
	{RybaRukaKyzyl: 0},
	{BoomRyba: 0},
	{BackgroundFootball: 0},
	{Твердый: 0},
	{FootGranitsa: 0},
	{FootPolya: 0},
	{FootVorota: 0},
	{FootKrug: 0},
	{FootUgol: 0},
	{FootLinii: 0},
	{Машина: 0},
	{FootballistKok: 0},
	{FootMyach: 0},
	{FootballistKyzyl: 0},
	{ДвижениеК: 0},
	{GDoroga: 0},
	{GDoroga2: 0},
	{Mesto: 0},
	{GMashinaKok: 0},
	{GMashinaKyzyl: 0},
	{GMashinaVrag: 0},
	{ChastitsDeath: 0},
	{ChastitsKok: 0},
	{ChastitsKyzyl: 0},
	{СледитьЗа: 0},
	{DashKamera: 0},
	{DashKok: 0},
	{Ugoll: 0},
	{DashKyzyl: 0},
	{DashSteny: 0},
	{DashSteny2: 0},
	{DashSteny3: 0},
	{Синусоида2: 0},
	{Kanat: 0},
	{KanatKok: 0},
	{KanatKok2: 0},
	{FishDno: 0},
	{FisherKok: 0},
	{FisherKyzyl: 0},
	{FishFish: 0},
	{FishWater: 0},
	{E: 0},
	{FKruchokKok: 0},
	{FKruchokKyzyl: 0},
	{FNitKok: 0},
	{FNitKyzyl: 0},
	{BackgroundCowboy: 0},
	{CowboyKok: 0},
	{CowboyKyzyl: 0},
	{CowPulya: 0},
	{CowZabor: 0},
	{Povorod: 0},
	{CPovorodKok: 0},
	{CPovorodKyzyl: 0},
	{Byk: 0},
	{CowPulyaKok: 0},
	{GMashinaVrag2: 0},
	{PDoroga: 0},
	{PDoroga2: 0},
	{PerehodKok: 0},
	{PerehodKyzyl: 0},
	{PZvezda: 0},
	{MKtank: 0},
	{MKrybalka: 0},
	{MKgonka: 0},
	{MKfootball: 0},
	{MKbull: 0},
	{MKkoshki: 0},
	{MKtank2: 0},
	{MKlotki: 0},
	{MKperehod: 0},
	{MKperestrelka: 0},
	{MKdash: 0},
	{MKkanat: 0},
	{MKballoon: 0},
	{MKbow: 0},
	{LotkaKok: 0},
	{ggh: 0},
	{LotkaKyzyl: 0},
	{Kray: 0},
	{FinishL: 0},
	{VodaRechka: 0},
	{VolnyLotki: 0},
	{VolnyLotkiBol: 0},
	{KokChet: 0},
	{KyzylChet: 0},
	{Sound: 0},
	{Player: 0},
	{Urovenn: 0},
	{Turnir: 0},
	{Tur2: 0},
	{TurVariant: 0},
	{Pryg: 0},
	{Vragii: 0},
	{Vragii2: 0},
	{GZvuk: 0},
	{VKok: 0},
	{Vkyzyl: 0},
	{Pryg2: 0},
	{Reklamna: 0},
	{Bbol: 0}
];

self.InstanceType = {
	KnopDom: class extends self.ISpriteInstance {},
	KnopPause: class extends self.ISpriteInstance {},
	KnopSound: class extends self.ISpriteInstance {},
	MiniSticki: class extends self.ISpriteInstance {},
	Yakorr: class extends self.ISpriteInstance {},
	Kozyrok: class extends self.ITiledBackgroundInstance {},
	TextKok: class extends self.ITextInstance {},
	TextKyzyl: class extends self.ITextInstance {},
	TextTimer: class extends self.ITextInstance {},
	WinKok: class extends self.ISpriteInstance {},
	WinKyzyl: class extends self.ISpriteInstance {},
	TextKyzylChet: class extends self.ITextInstance {},
	TextKokChet: class extends self.ITextInstance {},
	ItogKok: class extends self.ISpriteInstance {},
	ItogKyzyl: class extends self.ISpriteInstance {},
	KnopChel1: class extends self.ISpriteInstance {},
	KnopChel2: class extends self.ISpriteInstance {},
	KnopDomoy: class extends self.ISpriteInstance {},
	KnopPlay: class extends self.ISpriteInstance {},
	KnopReplay: class extends self.ISpriteInstance {},
	KnopTurnir: class extends self.ISpriteInstance {},
	BackgroundTank: class extends self.ITiledBackgroundInstance {},
	Derevo: class extends self.ISpriteInstance {},
	TankKok: class extends self.ISpriteInstance {},
	KirpichTail: class extends self.ITiledBackgroundInstance {},
	TankKyzyl: class extends self.ISpriteInstance {},
	PulyaTank: class extends self.ISpriteInstance {},
	BoomTank: class extends self.ISpriteInstance {},
	TankKyzyl2: class extends self.ISpriteInstance {},
	TankKok2: class extends self.ISpriteInstance {},
	BackgroundTank2: class extends self.ITiledBackgroundInstance {},
	OgradaTail: class extends self.ITiledBackgroundInstance {},
	PulyaKok: class extends self.ISpriteInstance {},
	PulyaKyzyl: class extends self.ISpriteInstance {},
	Blackground: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Kok: class extends self.ITiledBackgroundInstance {},
	Kyzyl: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Trigg: class extends self.ISpriteInstance {},
	Trigg2: class extends self.ISpriteInstance {},
	MFon: class extends self.ISpriteInstance {},
	MPodskazka: class extends self.ISpriteInstance {},
	MStrelka: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Winngga: class extends self.ISpriteInstance {},
	YandexGamesSDK: class extends self.IInstance {},
	LocalStor: class extends self.IInstance {},
	BalloonKok: class extends self.ISpriteInstance {},
	BalloonKyzyl: class extends self.ISpriteInstance {},
	BaSetkaKok: class extends self.ISpriteInstance {},
	BaSetkaKyzyl: class extends self.ISpriteInstance {},
	StenaKirpich: class extends self.ITiledBackgroundInstance {},
	BVolna: class extends self.ITiledBackgroundInstance {},
	BZvezda: class extends self.ISpriteInstance {},
	BVolna2: class extends self.ITiledBackgroundInstance {},
	BTochki: class extends self.ITiledBackgroundInstance {},
	ArrowKok: class extends self.ISpriteInstance {},
	BackgroundBow: class extends self.ISpriteInstance {},
	ArrowKyzyl: class extends self.ISpriteInstance {},
	BowKok: class extends self.ISpriteInstance {},
	BowKyzyl: class extends self.ISpriteInstance {},
	Ryba: class extends self.ISpriteInstance {},
	BackgroundLovi: class extends self.ITiledBackgroundInstance {},
	RybaRukaKok: class extends self.ISpriteInstance {},
	RybaRukaKyzyl: class extends self.ISpriteInstance {},
	BoomRyba: class extends self.ISpriteInstance {},
	BackgroundFootball: class extends self.ITiledBackgroundInstance {},
	FootGranitsa: class extends self.ITiledBackgroundInstance {},
	FootPolya: class extends self.ITiledBackgroundInstance {},
	FootVorota: class extends self.ISpriteInstance {},
	FootKrug: class extends self.ISpriteInstance {},
	FootUgol: class extends self.ISpriteInstance {},
	FootLinii: class extends self.ITiledBackgroundInstance {},
	FootballistKok: class extends self.ISpriteInstance {},
	FootMyach: class extends self.ISpriteInstance {},
	FootballistKyzyl: class extends self.ISpriteInstance {},
	GDoroga: class extends self.ITiledBackgroundInstance {},
	GDoroga2: class extends self.ITiledBackgroundInstance {},
	GMashinaKok: class extends self.ISpriteInstance {},
	GMashinaKyzyl: class extends self.ISpriteInstance {},
	GMashinaVrag: class extends self.ISpriteInstance {},
	ChastitsDeath: class extends self.IParticlesInstance {},
	ChastitsKok: class extends self.IParticlesInstance {},
	ChastitsKyzyl: class extends self.IParticlesInstance {},
	DashKamera: class extends self.ISpriteInstance {},
	DashKok: class extends self.ISpriteInstance {},
	DashKyzyl: class extends self.ISpriteInstance {},
	DashSteny: class extends self.ITiledBackgroundInstance {},
	DashSteny2: class extends self.ITiledBackgroundInstance {},
	DashSteny3: class extends self.ITiledBackgroundInstance {},
	Kanat: class extends self.ISpriteInstance {},
	KanatKok: class extends self.ISpriteInstance {},
	KanatKok2: class extends self.ISpriteInstance {},
	FishDno: class extends self.ITiledBackgroundInstance {},
	FisherKok: class extends self.ISpriteInstance {},
	FisherKyzyl: class extends self.ISpriteInstance {},
	FishFish: class extends self.ISpriteInstance {},
	FishWater: class extends self.ITiledBackgroundInstance {},
	FKruchokKok: class extends self.ISpriteInstance {},
	FKruchokKyzyl: class extends self.ISpriteInstance {},
	FNitKok: class extends self.ITiledBackgroundInstance {},
	FNitKyzyl: class extends self.ITiledBackgroundInstance {},
	BackgroundCowboy: class extends self.ITiledBackgroundInstance {},
	CowboyKok: class extends self.ISpriteInstance {},
	CowboyKyzyl: class extends self.ISpriteInstance {},
	CowPulya: class extends self.ISpriteInstance {},
	CowZabor: class extends self.ISpriteInstance {},
	CPovorodKok: class extends self.ISpriteInstance {},
	CPovorodKyzyl: class extends self.ISpriteInstance {},
	Byk: class extends self.ISpriteInstance {},
	CowPulyaKok: class extends self.ISpriteInstance {},
	GMashinaVrag2: class extends self.ISpriteInstance {},
	PDoroga: class extends self.ITiledBackgroundInstance {},
	PDoroga2: class extends self.ITiledBackgroundInstance {},
	PerehodKok: class extends self.ISpriteInstance {},
	PerehodKyzyl: class extends self.ISpriteInstance {},
	PZvezda: class extends self.ISpriteInstance {},
	MKtank: class extends self.ISpriteInstance {},
	MKrybalka: class extends self.ISpriteInstance {},
	MKgonka: class extends self.ISpriteInstance {},
	MKfootball: class extends self.ISpriteInstance {},
	MKbull: class extends self.ISpriteInstance {},
	MKkoshki: class extends self.ISpriteInstance {},
	MKtank2: class extends self.ISpriteInstance {},
	MKlotki: class extends self.ISpriteInstance {},
	MKperehod: class extends self.ISpriteInstance {},
	MKperestrelka: class extends self.ISpriteInstance {},
	MKdash: class extends self.ISpriteInstance {},
	MKkanat: class extends self.ISpriteInstance {},
	MKballoon: class extends self.ISpriteInstance {},
	MKbow: class extends self.ISpriteInstance {},
	LotkaKok: class extends self.ISpriteInstance {},
	LotkaKyzyl: class extends self.ISpriteInstance {},
	Kray: class extends self.ITiledBackgroundInstance {},
	FinishL: class extends self.ITiledBackgroundInstance {},
	VodaRechka: class extends self.ITiledBackgroundInstance {},
	VolnyLotki: class extends self.IParticlesInstance {},
	VolnyLotkiBol: class extends self.IParticlesInstance {}
}